version: "2.2"
services:
  echo:
    image: supersonictw/popcat-echo
    container_name: echo
    depends_on:
      - redis
      - mariadb
    networks:
      - echo
    environment:
      TZ: Asia/Taipei
      CORS_SUPPORT: "no"
      FRONTEND_SSL: "no"
      FRONTEND_HOSTNAME: ""
      REFRESH_INTERVAL: 10
      REFRESH_DELAY: 1
      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DBNAME: 0
      REDIS_NAMESPACE_POP: pop
      REDIS_NAMESPACE_GEO: geo
      REDIS_NAMESPACE_RATE: rate
      MYSQL_DSN: cat:example@tcp(mariadb)/popcat
      POP_JWT_SECRET: ""
      POP_JWT_EXPIRED: 20
      POP_RECAPTCHA_SECRET: ""
      POP_LIMIT_HTTP_DURATION: 0
      POP_LIMIT_HTTP_REQUESTS: 1
      POP_LIMIT_REDIS_DURATION: 0
      POP_LIMIT_REDIS_POP_COUNT: 800
      FORCE_FIX_RATE: "no"
    ports:
      - 127.0.0.1:8013:8013
    restart: always
  redis:
    image: redis
    container_name: redis
    networks:
      - echo
    restart: always
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - echo
    volumes:
      - database:/var/lib/mysql
      - ./initialize_db.sh:/initialize.sh:ro
    environment:
      MARIADB_USER: cat
      MARIADB_PASSWORD: example
      MARIADB_DATABASE: popcat
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    restart: always

volumes:
  database:
    driver: local

networks:
  echo:
    driver: bridge
