version: "2.2"
services:
  echo:
    image: supersonictw/popcat-echo
    container_name: echo
    networks:
      - echo
    environment:
      TZ: "Asia/Taipei"
  redis:
    image: redis
    container_name: redis
    networks:
      - echo
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - echo

networks:
  echo:
    driver: bridge
