version: "2.2"
services:
  echo:
    image: supersonictw/popcat-echo
    container_name: echo
    networks:
      - echo
    environment:
      TZ: Asia/Taipei
      REFRESH_INTERVAL: 10
      REFRESH_DELAY: 1
      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DBNAME: 0
      REDIS_NAMESPACE_POP: pop
      REDIS_NAMESPACE_GEO: geo
      MYSQL_DSN: cat:@tcp(mariadb)/popcat
      RECAPTCHA_SECRET: ""
      JWT_SECRET: ""
      JWT_EXPIRED: 20
      POP_LIMIT: 800
    ports:
      - 127.0.0.1:8013:8013
  redis:
    image: redis
    container_name: redis
    networks:
      - echo
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - echo
    volumes:
      - ./initialize_db.sh:/initialize.sh:ro
    environment:
      MARIADB_USER: cat
      MARIADB_PASSWORD: ""
      MARIADB_DATABASE: popcat
      MARIADB_RANDOM_ROOT_PASSWORD: "true"

networks:
  echo:
    driver: bridge
